2011-03-12 22:49:13,079 root         ERROR    Engine Crashed
Traceback (most recent call last):
  File "RxboxEngine.py", line 89, in <module>
    engine.run()
  File "RxboxEngine.py", line 53, in run
    self.rxboxDB.dbconnect()
  File "/home/luke/workspace/Rxbox1.0Beta/Modules/rxboxdb.py", line 33, in dbconnect
    db = "mysql")
  File "/usr/lib/pymodules/python2.6/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/pymodules/python2.6/MySQLdb/connections.py", line 170, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

